### ISSUE TITLE
希望能随机抽取发送欢迎消息

### ISSUE THREAD

**Issue by CleMooling** [JAs0n319/Welcome_MSG#1]
如题，希望能够自定义多条语句并在玩家进服时随机抽选一条发送。

**Comment by JAs0n319** [comment]
在近期会尝试添加
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月18日 00:57 |
| 收件人 | JAs0n319/Welcome_MSG ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [JAs0n319/Welcome_MSG] 希望能随机抽取发送欢迎消息 (Issue #1) |

如题，希望能够自定义多条语句并在玩家进服时随机抽选一条发送。

**Comment by JAs0n319** [comment]
已更新
